core/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name="index"),
    path('api/menu', views.get_json_menu, name="get_json_menu"),

]

news/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('blog', views.blog, name='blog'),
    path('blog/<int:pk>', views.blog_detail, name='blog_detail'),
]

rzsgymn/urls.py
from django.conf.urls.static import static, serve
from django.contrib import admin
from django.urls import path, include, re_path

from rzsgymn import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('news.urls')),
    path('', include('pages.urls')),
    path('', include('staff.urls')),
    path('tinymce/', include('tinymce.urls')),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/models.py
import os

from django.db import models
from django.utils.safestring import mark_safe
from tinymce.models import HTMLField
from staff.models import Person
from django.dispatch import receiver
from bs4 import BeautifulSoup

NUMBER_OF_CHARACTERS_PREVIOUS_NEWS = 200


class ImageOfPost(models.Model):
    class Meta:
        verbose_name_plural = 'Зображення для новин'

    __HEIGHT = 200
    __WEIGHT = 300

    image = models.ImageField(
        upload_to='image_of_post/%Y/%m',
        verbose_name='зображення',
        # help_text='фото має бути розміром 600x400 px',
    )

    news = models.ForeignKey(
        'News',
        on_delete=models.CASCADE,
        verbose_name='новина',
    )

    @property
    def show_image(self):
        if self.image:
            return mark_safe(f'<img src="{self.image.url}" width="{self.__WEIGHT}" height="{self.__HEIGHT}" />')
        return ""


@receiver(models.signals.post_delete, sender=ImageOfPost)
def auto_delete_file_on_delete(sender, instance, *args, **kwargs):
    """ Clean Old Image file """
    if instance.image:
        if os.path.isfile(instance.image.path):
            os.remove(instance.image.path)


@receiver(models.signals.pre_save, sender=ImageOfPost)
def pre_save_image(sender, instance, *args, **kwargs):
    """ instance old image file will delete from os """
    if not instance.pk:
        return False

    try:
        old_file = ImageOfPost.objects.get(pk=instance.pk).image
    except ImageOfPost.DoesNotExist:
        return False

    new_file = instance.image
    if not old_file == new_file:
        if os.path.isfile(old_file.path):
            os.remove(old_file.path)


class Categories(models.Model):
    class Meta:
        verbose_name_plural = 'Категорії'

    __HEIGHT = 100
    __WEIGHT = 150

    name = models.CharField(
        max_length=64,
        verbose_name='назва',
        help_text='перше слово має бути з великої літери',
        unique=True,
    )
    image = models.ImageField(
        upload_to='categories',
        verbose_name='зображення',
        help_text='фото має бути розміром 600x400 px',
    )

    def __str__(self):
        return self.name

    @property
    def show_image(self):
        if self.image:
            return mark_safe(f'<img src="{self.image.url}" width="{self.__WEIGHT}" height="{self.__HEIGHT}" />')
        return ""


@receiver(models.signals.post_delete, sender=Categories)
def auto_delete_file_on_delete(sender, instance, *args, **kwargs):
    """ Clean Old Image file """
    if instance.image:
        if os.path.isfile(instance.image.path):
            os.remove(instance.image.path)


@receiver(models.signals.pre_save, sender=Categories)
def pre_save_image(sender, instance, *args, **kwargs):
    """ instance old image file will delete from os """
    if not instance.pk:
        return False

    try:
        old_file = Categories.objects.get(pk=instance.pk).image
    except Categories.DoesNotExist:
        return False

    new_file = instance.image
    if not old_file == new_file:
        if os.path.isfile(old_file.path):
            os.remove(old_file.path)


class News(models.Model):
    class Meta:
        verbose_name_plural = 'Новини'

    title = models.CharField(max_length=64, verbose_name='Заголовок')
    author = models.ForeignKey(
        Person,
        on_delete=models.PROTECT,
        verbose_name='автор',
    )
    categories = models.ForeignKey(
        'Categories',
        on_delete=models.PROTECT,
        verbose_name='категорія',
    )
    # images
    content = HTMLField()
    date_created = models.DateField(verbose_name='Дата публікації')
    is_published = models.BooleanField(default=True, verbose_name='Публікувати')
    number_of_views = models.PositiveIntegerField(default=0, verbose_name='Кількість переглядів')

    def __str__(self):
        return self.title[:20]

    def get_author(self):
        return self.author.get_initials()

    def preview_content(self):
        soup_text = BeautifulSoup(self.content, 'html.parser').text
        if len(soup_text) > NUMBER_OF_CHARACTERS_PREVIOUS_NEWS:
            return soup_text[:NUMBER_OF_CHARACTERS_PREVIOUS_NEWS] + '...'
        return soup_text

news/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404
from .models import News, Categories

COUNT_NEWS_OF_PAGE = 9


def blog(request):
    # print(dir(request))
    # print(request.COOKIES)
    # print(request.META)
    active_category = request.GET.get('cat', '')

    if active_category:
        news = News.objects.filter(categories__name=active_category).filter(is_published=True).order_by('-date_created')
    else:
        news = News.objects.filter(is_published=True).order_by('-date_created')
    paginator = Paginator(news, COUNT_NEWS_OF_PAGE)
    page_number = validator_of_positive_numbers(request.GET.get('page', '1'))

    page_obj = paginator.get_page(page_number)

    end_n = paginator.page_range.stop - 1
    if page_number > end_n:
        page_number = end_n

    class_first_page, class_last_page, list_of_pages = get_list_of_pages(page_number, end_n)
    context = {
        'news': page_obj.object_list,
        'categories': Categories.objects.all(),
        'active_category': active_category,
        'list_of_pages': list_of_pages,
        'class_first_page': class_first_page,
        'class_last_page': class_last_page,
        'page_number': page_number,
        'next_link': page_number + 1,
        'previous_link': page_number - 1,
    }
    return render(request, 'news/blog.html', context=context)


def blog_detail(request, pk):
    post = get_object_or_404(News, pk=pk)
    if post.number_of_views < 10 ** 6:
        post.number_of_views += 1
        post.save()
    images_of_post = post.imageofpost_set.all()
    count_image = images_of_post.count()
    related_posts = News.objects.filter(categories__name=post.categories).order_by('-date_created')[:4]
    context = {
        'post': post,
        'images_of_post': images_of_post,
        'count_image': count_image,
        'related_posts': [obj for obj in related_posts if obj.pk != post.pk],
        'list_range_count_image': list(range(1, count_image)),
        'categories': Categories.objects.order_by('name'),
    }

    return render(request, 'news/single.html', context=context)


def get_list_of_pages(active_n: int, end_n: int) -> tuple:
    """
    :param active_n: active number of page
    :param end_n: end number of page
    :return: first class name, last class name, list for render html
    get_list_of_pages(1, 3) == 'disabled', '', [1, 2, 3]
    get_list_of_pages(55, 100) == '', '', [1, 2, 0, 53, 54, 55, 56, 57, 0, 99, 100]
    """

    lst = []
    if active_n <= 5:
        [lst.append(n) for n in range(1, active_n)]
    else:
        lst.extend([1, 2, 0, active_n - 2, active_n - 1])

    if active_n + 5 >= end_n:
        [lst.append(n) for n in range(active_n, end_n + 1)]
    else:
        lst.extend([active_n, active_n + 1, active_n + 2, 0, end_n - 1, end_n])
    return (
        'disabled' if active_n == 1 else '',
        'disabled' if active_n == end_n else '',
        lst,
    )


def validator_of_positive_numbers(n: str) -> int:
    if len(set(n) - set('0123456789')) == 0:
        return int(n)
    return 1

news/templates/news/blog.html
{% extends 'base.html' %}
{% load static %}

{% block link %}
<link href="{% static 'css/categories.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
<!-- Header Start -->
<div class="container-fluid bg-primary mb-5">
    <div class="d-flex flex-column align-items-center justify-content-center" style="min-height: 400px">
        <h3 class="display-3 font-weight-bold text-white">Наші новини</h3>
        <div class="d-inline-flex text-white">
            <span><a class="text-white" href="{% url 'index' %}">Головна</a></span>
            <span class="px-2">/</span>
            <span><a class="text-white" href="{% url 'blog' %}">Наші новини</a></span>
            {% if active_category %}
            <span class="px-2">/</span>
            <span>{{ active_category }}</span>
            {% endif %}
        </div>
    </div>
</div>
<!-- Header End -->


<!-- Blog Start -->
<div class="container-fluid pt-5">
    <div class="container">
        <div class="text-center pb-2">
            <p class="section-title px-5"><span class="px-2">Останні новини</span></p>
            <h1 class="mb-4">Останні новини нашого блогу</h1>
        </div>


        <!--Categories Start-->
        <div class="row">
            <div class="col-12 text-center mb-2">
                <div class="list-inline mb-4" id="portfolio-flters">
                    <a class="btn category_link m-1 category_link_active" href="{% url 'blog' %}">Всі</a>
                    {% for category in categories|dictsort:'name' %}
                    <a class="btn category_link m-1" href="{% url 'blog' %}?cat={{ category.name }}">{{ category.name }}</a>
                    {% endfor %}
                </div>
            </div>
        </div>
        <!--Categories End-->


        {% include  'show_news.html' %}
        <div class="col-md-12 mb-4">
            <nav aria-label="Page navigation">
              <ul class="pagination justify-content-center mb-0">
                  <li class="page-item {{ class_first_page }}">
                      <a class="page-link" href="{% url 'blog' %}?page={{ previous_link }}&cat={{ active_category }}" aria-label="Previous">
                          <span aria-hidden="true">&laquo;</span>
                          <span class="sr-only">Previous</span>
                      </a>
                  </li>
                  {% for n in list_of_pages %}
                  {% if n == page_number%}
                  <li class="page-item active"><a class="page-link" href="{% url 'blog' %}?page={{ n }}&cat={{ active_category }}">{{ n }}</a></li>
                  {% elif n == 0 %}
                  <li class="page-item page-link">...</li>
                  {% else %}
                  <li class="page-item"><a class="page-link" href="{% url 'blog' %}?page={{ n }}&cat={{ active_category }}">{{ n }}</a></li>
                  {% endif %}

                  {% endfor %}
                  <li class="page-item {{ class_last_page }}">
                      <a class="page-link" href="{% url 'blog' %}?page={{ next_link }}&cat={{ active_category }}" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                        <span class="sr-only">Next</span>
                      </a>
                  </li>
              </ul>
            </nav>
        </div>
    </div>
</div>

<!-- Blog End -->
{% endblock %}

{% block script %}
    let active_category = '{{ active_category }}';
    let children_cat = document.getElementById('portfolio-flters').children;
    for (let i = 1; i < children_cat.length; i++) {
        if (children_cat[i].text == active_category) {
            children_cat[i].classList.toggle('category_link_active');
            children_cat[0].classList.toggle('category_link_active');
            break;
        }
    }
{% endblock %}

news/templates/news/single.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container-fluid bg-primary mb-5">
    <div class="d-flex flex-column align-items-center justify-content-center" style="min-height: 400px">
        <h3 class="display-3 font-weight-bold text-white">Сторінка Новини</h3>
        <div class="d-inline-flex text-white">
            <p class="m-0"><a class="text-white" href="">Home</a></p>
            <p class="m-0 px-2">/</p>
            <p class="m-0">Blog Detail</p>
        </div>
    </div>
</div>
<!-- Header End -->


<!-- Detail Start -->
<div class="container pb-5">
    <div class="row pt-5">
        <div class="col-lg-8">
            <div class="d-flex flex-column text-left mb-3">
                <p class="section-title pr-5"><span class="pr-2">Сторінка новини</span></p>
                <h1 class="mb-3">{{ post.title }}</h1>
                <div class="d-sm-flex">
                    <p class="mr-3"><i class="fa fa-user text-primary"></i> {{ post.author.get_initials }}</p>
                    <p class="mr-3"><i class="fa fa-folder text-primary"></i> {{ post.categories.name }}</p>
                    <p class="mr-3"><i class="fa fa-calendar-day text-primary"></i> {{ post.date_created }}</p>
                </div>
            </div>
            <div class="mb-5">

                {% if count_image == 1 %}
                <img class="img-fluid rounded w-100 mb-4" src="{{ images_of_post.first.image.url }}" alt="Image">
                {% elif count_image > 1 %}

                <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                    <ol class="carousel-indicators">
                        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                        {% for n in list_range_count_image %}
                        <li data-target="#carouselExampleIndicators" data-slide-to="{{ n }}"></li>
                        {% endfor %}
                    </ol>

                    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                    <div class="carousel-inner" id="carousel-inner">
                        {% for img in images_of_post %}
                        <div class="carousel-item">
                            <img class="d-block w-100" src="{{ img.image.url }}" alt="item slide">
                        </div>
                        {% endfor %}

                    </div>
                </div>
                {% endif %}

                {{ post.content|safe }}

            </div>

            {% if related_posts %}
            <!-- Related Post -->
            <div class="mb-5 mx-n3">
                <h2 class="mb-4 ml-3">Схожі новини</h2>
                <div class="owl-carousel post-carousel position-relative">

                    {% for related_post in related_posts %}

                    <div class="d-flex align-items-center bg-light shadow-sm rounded overflow-hidden mx-3">

                        {% with img_obj=related_post.imageofpost_set.first %}
                        {% if img_obj %}
                        <img class="img-fluid" src="{{ img_obj.image.url }}" style="width: 80px; height: 80px;"
                             alt="related_post_image">
                        {% else %}
                        <img class="img-fluid" src="{{ post.categories.image.url }}" style="width: 80px; height: 80px;"
                             alt="related_post_image">
                        {% endif %}
                        {% endwith %}

                        <div class="pl-3">
                            {% if related_post.title|length > 20 %}
                            <h5>
                                <a href="{% url 'blog_detail' related_post.pk %}" class="text-dark">
                                    {{ related_post.title|slice:20 }}...
                                </a>
                            </h5>
                            {% else %}
                            <h5>
                                <a href="{% url 'blog_detail' related_post.pk %}" class="text-dark">
                                    {{ related_post.title }}
                                </a>
                            </h5>
                            {% endif %}
                            <div>
                                <small class="mr-3">
                                    <i class="fa fa-user text-primary"></i>
                                    {{ related_post.author.get_initials }}
                                </small>
                                <br>
                                <small class="mr-3">
                                    <i class="fa fa-folder text-primary"></i>
                                    {{ related_post.date_created|date:"Y-m-d" }}
                                </small>
                            </div>
                        </div>
                    </div>
                    {% endfor %}

                </div>
            </div>
            {% endif %}

        </div>

        <div class="col-lg-4 mt-5 mt-lg-0">

            <!-- Author Bio -->
            <div class="d-flex flex-column text-center bg-primary rounded mb-5 py-5 px-4">

                <img src="{{ post.author.photo.url }}" class="img-fluid rounded-circle mx-auto mb-3" style="width: 100px;" alt="author">

                {% with author=post.author %}
                <h3 class="text-secondary mb-3">
                    <a href="{% url 'staff_detail' author.pk %}" class="text-white">
                        {{ author.get_initials }}
                    </a>
                </h3>
                {% if author.life_credo %}
                <p class="text-white m-0">{{ author.life_credo }}</p>
                {% endif %}
                {% endwith %}

            </div>

            <!-- Keyword -->
<!--            <div class="mb-5">-->
<!--                <form action="">-->
<!--                    <div class="input-group">-->
<!--                        <input type="text" class="form-control form-control-lg" placeholder="Keyword">-->
<!--                        <div class="input-group-append">-->
<!--                            <span class="input-group-text bg-transparent text-primary"><i-->
<!--                                    class="fa fa-search"></i></span>-->
<!--                        </div>-->
<!--                    </div>-->
<!--                </form>-->
<!--            </div>-->

            <!-- Category List -->
            <div class="mb-5">
                <h2 class="mb-4">Категорії</h2>
                <ul class="list-group list-group-flush">
                    {% for category in categories %}
                    <li class="list-group-item d-flex justify-content-between align-items-center px-0">
                        <a href="{% url 'blog' %}?cat={{ category.name }}">{{ category.name }}</a>
                        <span class="badge badge-primary badge-pill">{{ category.news_set.count }}</span>
                    </li>
                    {% endfor %}
                </ul>
            </div>

            <!-- Single Image -->
            <!--                <div class="mb-5">-->
            <!--                    <img src="img/blog-1.jpg" alt="" class="img-fluid rounded">-->
            <!--                </div>-->


            <!-- Single Image -->
            <!--                <div class="mb-5">-->
            <!--                    <img src="img/blog-3.jpg" alt="" class="img-fluid rounded">-->
            <!--                </div>-->

            <!-- Plain Text -->
            <!--                <div>-->
            <!--                    <h2 class="mb-4">Plain Text</h2>-->
            <!--                    Aliquyam sed lorem stet diam dolor sed ut sit. Ut sanctus erat ea est aliquyam dolor et. Et no consetetur eos labore ea erat voluptua et. Et aliquyam dolore sed erat. Magna sanctus sed eos tempor rebum dolor, tempor takimata clita sit et elitr ut eirmod.-->
            <!--                </div>-->

        </div>
    </div>
</div>
<!-- Detail End -->
{% endblock %}

{% block script %}
<script>
    window.onload=function(e){
        let el = document.getElementById('carousel-inner')
        el.firstElementChild.classList.add('active')
    }
</script>
{% endblock %}