core/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name="index"),
    path('api/menu', views.get_json_menu, name="get_json_menu"),

]

rzsgymn/urls.py
from django.conf.urls.static import static, serve
from django.contrib import admin
from django.urls import path, include, re_path

from rzsgymn import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('news.urls')),
    path('', include('pages.urls')),
    path('', include('staff.urls')),
    path('tinymce/', include('tinymce.urls')),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/models.py
import os

from django.db import models
from django.utils.safestring import mark_safe
from tinymce.models import HTMLField
from staff.models import Person
from django.dispatch import receiver
from bs4 import BeautifulSoup

NUMBER_OF_CHARACTERS_PREVIOUS_NEWS = 200


class ImageOfPost(models.Model):
    class Meta:
        verbose_name_plural = 'Зображення для новин'

    __HEIGHT = 200
    __WEIGHT = 300

    image = models.ImageField(
        upload_to='image_of_post/%Y/%m',
        verbose_name='зображення',
        # help_text='фото має бути розміром 600x400 px',
    )

    news = models.ForeignKey(
        'News',
        on_delete=models.CASCADE,
        verbose_name='новина',
    )

    @property
    def show_image(self):
        if self.image:
            return mark_safe(f'<img src="{self.image.url}" width="{self.__WEIGHT}" height="{self.__HEIGHT}" />')
        return ""


@receiver(models.signals.post_delete, sender=ImageOfPost)
def auto_delete_file_on_delete(sender, instance, *args, **kwargs):
    """ Clean Old Image file """
    if instance.image:
        if os.path.isfile(instance.image.path):
            os.remove(instance.image.path)


@receiver(models.signals.pre_save, sender=ImageOfPost)
def pre_save_image(sender, instance, *args, **kwargs):
    """ instance old image file will delete from os """
    if not instance.pk:
        return False

    try:
        old_file = ImageOfPost.objects.get(pk=instance.pk).image
    except ImageOfPost.DoesNotExist:
        return False

    new_file = instance.image
    if not old_file == new_file:
        if os.path.isfile(old_file.path):
            os.remove(old_file.path)


class Categories(models.Model):
    class Meta:
        verbose_name_plural = 'Категорії'

    __HEIGHT = 100
    __WEIGHT = 150

    name = models.CharField(
        max_length=64,
        verbose_name='назва',
        help_text='перше слово має бути з великої літери',
        unique=True,
    )
    image = models.ImageField(
        upload_to='categories',
        verbose_name='зображення',
        help_text='фото має бути розміром 600x400 px',
    )

    def __str__(self):
        return self.name

    @property
    def show_image(self):
        if self.image:
            return mark_safe(f'<img src="{self.image.url}" width="{self.__WEIGHT}" height="{self.__HEIGHT}" />')
        return ""


@receiver(models.signals.post_delete, sender=Categories)
def auto_delete_file_on_delete(sender, instance, *args, **kwargs):
    """ Clean Old Image file """
    if instance.image:
        if os.path.isfile(instance.image.path):
            os.remove(instance.image.path)


@receiver(models.signals.pre_save, sender=Categories)
def pre_save_image(sender, instance, *args, **kwargs):
    """ instance old image file will delete from os """
    if not instance.pk:
        return False

    try:
        old_file = Categories.objects.get(pk=instance.pk).image
    except Categories.DoesNotExist:
        return False

    new_file = instance.image
    if not old_file == new_file:
        if os.path.isfile(old_file.path):
            os.remove(old_file.path)


class News(models.Model):
    class Meta:
        verbose_name_plural = 'Новини'

    title = models.CharField(max_length=64, verbose_name='Заголовок')
    author = models.ForeignKey(
        Person,
        on_delete=models.PROTECT,
        verbose_name='автор',
    )
    categories = models.ForeignKey(
        'Categories',
        on_delete=models.PROTECT,
        verbose_name='категорія',
    )
    # images
    content = HTMLField()
    date_created = models.DateField(verbose_name='Дата публікації')
    is_published = models.BooleanField(default=True, verbose_name='Публікувати')
    number_of_views = models.PositiveIntegerField(default=0, verbose_name='Кількість переглядів')

    def __str__(self):
        return self.title[:20]

    def get_author(self):
        return self.author.get_initials()

    def preview_content(self):
        soup_text = BeautifulSoup(self.content, 'html.parser').text
        if len(soup_text) > NUMBER_OF_CHARACTERS_PREVIOUS_NEWS:
            return soup_text[:NUMBER_OF_CHARACTERS_PREVIOUS_NEWS] + '...'
        return soup_text

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="uk">
<head>
    <meta charset="utf-8">
    <title>Розсошенська гімназія - Головна сторінка</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="Розсошенська гімназія" name="keywords">
    <meta content="12  вересня 1993 року була відкрита Розсошенська загальноосвітня школа І-ІІІ ступенів. Із 2002 року вона реорганізована у Розсошенську гімназію, а з 2019 року – Комунальний заклад «Розсошенська гімназія Щербанівської сільської ради Полтавського району Полтавської області»" name="description">

    <!-- Favicon -->
    <link href="{% static 'img/favicon.ico' %}" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Handlee&family=Nunito&display=swap&subset=cyrillic-ext" rel="stylesheet">

    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">

    <!-- Flaticon Font -->
    <link href="{% static 'lib/flaticon/font/flaticon.css' %}" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
    <!-- <link href="{% static 'lib/lightbox/css/lightbox.min.css' %}" rel="stylesheet"> -->

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{% static 'css/additional_style.css' %}" rel="stylesheet">

    {% block link %}
    {% endblock %}

</head>

<body>
<!-- Navbar Start -->
<div class="container-fluid bg-light position-relative shadow">
    <nav class="navbar navbar-expand-lg bg-light navbar-light py-3 py-lg-0 px-0 px-lg-5">
        <a href="{% url 'index' %}" class="navbar-brand font-weight-bold text-secondary" style="font-size: 50px;">
            <img src="{% static 'img/logo.svg' %}" alt="logo">
            <!-- <span class="text-primary">КЗ Розсошенці</span> -->
        </a>
        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
            <div class="navbar-nav font-weight-bold mx-auto py-0" id="mainMenu">
                <a href="{% url 'index' %}" class="nav-item nav-link">Головна</a>
                <a href="{% url 'blog' %}" class="nav-item nav-link">Новини</a>
                <a href="{% url 'staff' %}" class="nav-item nav-link">Колектив</a>
                <!--  <div class="nav-item dropdown">
                     <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">Pages</a>
                     <div class="dropdown-menu rounded-0 m-0">
                         <a href="blog.html" class="dropdown-item">Blog Grid</a>
                         <a href="single.html" class="dropdown-item">Blog Detail</a>
                     </div>
                 </div> -->
            </div>
            <!-- <a href="" class="btn btn-primary px-4">Join Class</a> -->
        </div>
    </nav>
</div>
<!-- Navbar End -->

{% block content %}
{% endblock %}

<!-- Footer Start -->
<footer class="container-fluid bg-secondary text-white mt-5 py-5 px-sm-3 px-md-5">
    <div class="row pt-5">
        <div class="col-lg-3 col-md-6 mb-5">
            <h3 class="text-primary mb-4">Головна ідея</h3>
            <!-- <a href="" class="navbar-brand font-weight-bold text-primary m-0 mb-4 p-0" style="font-size: 40px; line-height: 40px;">
                <i class="flaticon-043-teddy-bear"></i>
                <img src="img/logo.svg" alt="logo">
                <span class="text-white">KidKinder</span>
            </a> -->
            <p>Labore dolor amet ipsum ea, erat sit ipsum duo eos. Volup amet ea dolor et magna dolor, elitr rebum duo
                est sed diam elitr. Stet elitr stet diam duo eos rebum ipsum diam ipsum elitr.</p>
            <div class="d-flex justify-content-start mt-4">
                <a class="btn btn-outline-primary rounded-circle text-center mr-2 px-0"
                   style="width: 38px; height: 38px;" href="https://www.facebook.com/profile.php?id=100037746100748"
                   target="_blank">
                    <i class="fab fa-facebook-f"></i>
                </a>
                <!--                    <a class="btn btn-outline-primary rounded-circle text-center mr-2 px-0"-->
                <!--                        style="width: 38px; height: 38px;" href="#"><i class="fab fa-instagram"></i></a>-->
                <a class="btn btn-outline-primary rounded-circle text-center mr-2 px-0"
                   style="width: 38px; height: 38px;" href="https://www.youtube.com/user/RzsGymn" target="_blank"><i
                        class="fab fa-youtube"></i></a>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 mb-5">
            <h3 class="text-primary mb-4">Наші Координати</h3>
            <div class="d-flex">
                <i class="fa fa-map-marker-alt text-primary footer-ico"></i>
                <div class="pl-3">
                    <h5 class="text-white">Адреса</h5>
                    <p>
                        38751 вул. Шкільна, 18
                        с. Розсошенці
                        Полтавського району
                        Полтавської області
                    </p>
                </div>
            </div>
            <div class="d-flex">
                <i class="fa fa-envelope text-primary footer-ico"></i>
                <div class="pl-3">
                    <h5 class="text-white">Email</h5>
                    <p><a href="mailto:rzsgymn@gmail.com" style="color:white">rzsgymn@gmail.com</a></p>
                </div>
            </div>
            <div class="d-flex">
                <i class="fa fa-phone-alt text-primary footer-ico"></i>
                <div class="pl-3">
                    <h5 class="text-white">Телефон</h5>
                    <p><a href="tel:0532590214" style="color:white">0532 590214</a></p>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 mb-5">
            <h3 class="text-primary mb-4">Про нас</h3>
            <div class="d-flex flex-column justify-content-start" id="footer_menu_row1"></div>
        </div>
        <div class="col-lg-3 col-md-6 mb-5">
            <h3 class="text-primary mb-4">Учням та батькам</h3>
            <div class="d-flex flex-column justify-content-start" id="footer_menu_row2"></div>
        </div>
    </div>
    <div class="container-fluid pt-5" style="border-top: 1px solid rgba(23, 162, 184, .2);;">
        <p class="m-0 text-center text-white">
            &copy; <a class="text-primary font-weight-bold" href="#">Розсошенська гімназія</a>. Всі права захищені.
            Спроектований
            <a class="text-primary font-weight-bold" href="https://htmlcodex.com">HTML Codex</a>
        </p>
    </div>
</footer>
<!-- Footer End -->


<!-- Back to Top -->
<a href="#" class="btn btn-primary p-3 back-to-top"><i class="fa fa-angle-double-up"></i></a>


<!-- JavaScript Libraries -->
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
<script src="{% static 'lib/easing/easing.min.js' %}"></script>
<script src="{% static 'lib/owlcarousel/owl.carousel.min.js' %}"></script>
<script src="{% static 'lib/isotope/isotope.pkgd.min.js' %}"></script>
<!-- <script src="{% static 'lib/lightbox/js/lightbox.min.js' %}"></script> -->

<!-- Contact Javascript File -->
<!--    <script src="{% static 'mail/jqBootstrapValidation.min.js' %}"></script>-->
<!--    <script src="{% static 'mail/contact.js' %}"></script>-->

<!-- Template Javascript -->
<script src="{% static 'js/main.js' %}"></script>
<script>
    window.onload=function(e){
        {% block script %}
        {% endblock %}
    };
</script>

</body>
</html>

templates/show_news.html
{% if news.count == 0 %}
<h2 class="text-center">Нажіль нічого не знайдено :(</h2>
{% else %}
<div class="row pb-3">
    {% for post in news %}
    <div class="col-lg-4 mb-4">
        <div class="card border-0 shadow-sm mb-2">

            {% with img_obj=post.imageofpost_set.first %}
            {% if img_obj %}
            <img class="card-img-top mb-2" src="{{ img_obj.image.url }}" alt="">
            {% else %}
            <img class="card-img-top mb-2" src="{{ post.categories.image.url }}" alt="">
            {% endif %}
            {% endwith %}

            <div class="card-body bg-light text-center p-4">
                <h4 class="">{{ post.title }}</h4>
                <div class="d-flex justify-content-center ">
                    <small class="mr-3"><i class="fa fa-user text-primary"></i> {{ post.author.get_initials }}</small>
                    <small class="mr-3"><i class="fa fa-folder text-primary"></i> {{ post.categories.name }}</small>
                </div>
                <div class="mb-3">
                    <small class="mr-3"><i class="fa fa-calendar-day text-primary"></i> {{ post.date_created }}</small>
                    <!--                            |date:"Y-m-d"-->
                    <i class="fa-solid fa-calendar-days"></i>
                </div>
                <div>{{ post.preview_content }}</div>
                <a href="{% url 'blog_detail' post.pk %}" class="btn btn-primary px-4 mx-auto my-2">Читати далі</a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endif %}