core/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name="index"),
    path('api/menu', views.get_json_menu, name="get_json_menu"),

]

rzsgymn/urls.py
from django.conf.urls.static import static, serve
from django.contrib import admin
from django.urls import path, include, re_path

from rzsgymn import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('news.urls')),
    path('', include('pages.urls')),
    path('', include('staff.urls')),
    path('tinymce/', include('tinymce.urls')),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

staff/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('staff', views.staff, name='staff'),
    path('staff/<int:pk>', views.staff_detail, name='staff_detail'),
]

other_staff/models.py
from django.db import models

from staff.models import Person


class Category(models.Model):
    class Meta:
        verbose_name_plural = 'Категорії'

    name = models.CharField(
        max_length=64,
        unique=True,
        verbose_name="назва (однина)",
        help_text='Приклад: Психолог',
    )

    names = models.CharField(
        max_length=64,
        unique=True,
        verbose_name="назва (множина)",
        help_text='Приклад: Психологи',
    )

    def __str__(self):
        return self.name


class OtherStaff(models.Model):
    class Meta:
        verbose_name_plural = 'Інші працівники'

    person = models.OneToOneField(
        Person,
        on_delete=models.CASCADE,
        verbose_name='Працівник',
    )

    categories = models.ManyToManyField(Category, verbose_name="категорії")

    def __str__(self):
        return self.person.get_fullname()

staff/models.py
import os

from django.db import models
from django.dispatch import receiver
from django.utils.html import mark_safe
from tinymce.models import HTMLField


class TypeOfSocialNetwork(models.Model):
    class Meta:
        verbose_name_plural = "Види соціальних мереж"

    name = models.CharField(max_length=32, verbose_name='назва', unique=True)
    class_name = models.CharField(
        max_length=32,
        help_text='назви класів шукайте за посиланням https://fortawesome.com/sets/font-awesome-5-brands or https://fontawesome.com/',
        verbose_name="ім'я класу",
        unique=True,
    )

    def __str__(self):
        return self.name


class SocialNetworkOfUser(models.Model):
    class Meta:
        verbose_name_plural = "Соціальні мережі користувачів"

    type_of_social_network = models.ForeignKey(
        'TypeOfSocialNetwork',
        on_delete=models.CASCADE,
        verbose_name='Вид соціальної мережі'
    )
    link = models.CharField(max_length=255)
    person = models.ForeignKey('Person', on_delete=models.CASCADE)

    def __str__(self):
        return self.type_of_social_network.name


class Person(models.Model):
    class Meta:
        verbose_name_plural = "Працівники"

    __SIZE_PHOTO = 80

    liberated = models.BooleanField(default=True, verbose_name='працює')

    # sex = models.CharField(
    #     max_length=36,
    #     choices=(
    #         ('woman', 'жіноча'),
    #         ('man', 'чоловіча'),
    #     ),
    #     verbose_name='стать'
    # )

    sex = models.SmallIntegerField(
        choices=(
            (0, 'жіноча'),
            (1, 'чоловіча'),
        ),
        verbose_name='стать'
    )

    lastname = models.CharField(max_length=32, verbose_name="прізвище")
    firstname = models.CharField(max_length=32, verbose_name="ім'я")
    patronymic = models.CharField(max_length=32, verbose_name="по батькові")

    photo = models.ImageField(
        upload_to='staff',
        verbose_name='фото',
        help_text='фото має бути розміром 300x300 px',
        # null=True,
        # blank=True
    )

    birthday = models.DateField()
    phone = models.CharField(max_length=16, null=True, blank=True, verbose_name='телефон')
    other_phone = models.CharField(max_length=16, null=True, blank=True, verbose_name='додатковий телефон')

    life_credo = models.CharField(
        max_length=256,
        null=True,
        blank=True,
        verbose_name='Життєве кредо',
        # help_text=''
    )

    about_me = HTMLField(
        null=True,
        blank=True,
        verbose_name='Про себе',
        # help_text=''
    )

    def __str__(self):
        return self.get_initials()

    def get_initials(self):
        return f'{self.lastname} {self.firstname[0]}. {self.patronymic[0]}.'

    def get_fullname(self):
        return f'{self.lastname} {self.firstname} {self.patronymic}'


    @property
    def show_photo(self):
        if self.photo:
            return mark_safe(f'<img src="{self.photo.url}" width="{self.__SIZE_PHOTO}" height="{self.__SIZE_PHOTO}" />')
        return mark_safe(f'<img src="/static/img/user.png" width="{self.__SIZE_PHOTO}" height="{self.__SIZE_PHOTO}" />')


@receiver(models.signals.post_delete, sender=Person)
def auto_delete_file_on_delete(sender, instance, *args, **kwargs):
    """ Clean Old Image file """
    if instance.photo:
        if os.path.isfile(instance.photo.path):
            os.remove(instance.photo.path)


@receiver(models.signals.pre_save, sender=Person)
def pre_save_image(sender, instance, *args, **kwargs):
    """ instance old image file will delete from os """
    if not instance.pk:
        return False

    try:
        old_file = Person.objects.get(pk=instance.pk).photo
    except Person.DoesNotExist:
        return False

    new_file = instance.photo
    if not old_file == new_file:
        if os.path.isfile(old_file.path):
            os.remove(old_file.path)

teachers/models.py
from django.db import models

from staff.models import Person


class Lesson(models.Model):
    class Meta:
        verbose_name_plural = 'Уроки'

    name = models.CharField(max_length=64, unique=True, verbose_name="назва", help_text='приклад: математика')

    genitive_case_of_name = models.CharField(
        max_length=64,
        unique=True,
        verbose_name="родовий відмінок",
        help_text='приклад: математики'
    )

    def __str__(self):
        return self.genitive_case_of_name


class Category(models.Model):
    class Meta:
        verbose_name_plural = 'Категорії'

    name = models.CharField(max_length=64, unique=True, verbose_name="назва")

    mass = models.SmallIntegerField(
        default=0,
        unique=True,
        verbose_name='ранг',
        help_text='ранг має бути унікальним для кожногї категорії'
    )

    def __str__(self):
        return self.name


class Rank(models.Model):
    class Meta:
        verbose_name_plural = 'Звання'

    name = models.CharField(max_length=64, unique=True, verbose_name="назва")

    def __str__(self):
        return self.name


class Teacher(models.Model):
    class Meta:
        verbose_name_plural = 'Вчителі'

    person = models.OneToOneField(
        Person,
        on_delete=models.CASCADE,
        verbose_name='Працівник',
    )

    lessons = models.ManyToManyField(Lesson, verbose_name="уроки", blank=True)

    categories = models.ForeignKey(Category, on_delete=models.PROTECT, verbose_name="категорія")

    ranks = models.ManyToManyField(
        Rank,
        blank=True,
        verbose_name="звання"
    )

    def __str__(self):
        return self.person.get_fullname()

staff/views.py
from django.shortcuts import render, get_object_or_404

from .models import Person
from teachers.models import Lesson, Category
from administration.models import Administration
from teachers.models import Teacher
from other_staff.models import Category as CategoryOtherOfStaff


def staff(request):
    active_category = request.GET.get('cat', '')
    if not active_category:
        persons = Person.objects.filter(liberated=True).order_by('lastname')
    if active_category == 'Адміністрація':
        persons = [admin.person for admin in Administration.objects.order_by('person__lastname')]
    elif active_category == 'Вчителі':
        persons = [teacher.person for teacher in Teacher.objects.order_by('person__lastname')]
    elif active_category:
        persons = []
        cat = CategoryOtherOfStaff.objects.filter(name=active_category).first()
        if not cat:
            cat = CategoryOtherOfStaff.objects.filter(names=active_category).first()
        if cat:
            persons = [other_staff.person for other_staff in cat.otherstaff_set.all().order_by('person__lastname')]

    context = {
        'persons': persons,
        'active_category': active_category,
        'cat_other_staff': CategoryOtherOfStaff.objects.order_by('name'),
    }
    return render(request, 'staff/staff.html', context=context)


def staff_detail(request, pk):
    person = get_object_or_404(Person, pk=pk)

    info_about_teacher = None
    if hasattr(person, 'teacher'):
        teacher_category = person.teacher.categories
        teacher_ranks = ', '.join(map(str, person.teacher.ranks.all()))
        info_about_teacher = f'{teacher_category}, {teacher_ranks}' if teacher_ranks else teacher_category

    context = {
        'person': person,
        'info_about_teacher': info_about_teacher,
        'certificates': person.certificate_set.order_by('-date'),
        'lessons': Lesson.objects.order_by('name'),
        'categories': Category.objects.order_by('-mass'),
    }
    return render(request, 'staff/single.html', context=context)

staff/templates/staff/single.html
{% extends 'base.html' %}
{% load static %}

{% block link %}
<link href="{% static 'css/categories.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
<!-- Header Start -->
<div class="container-fluid bg-primary mb-5">
    <div class="container">
        <!--        <img src="/media/staff/team-4.jpg" class="img-fluid rounded-circle mx-auto mb-3" style="width: 500px;">-->
        <div class="row py-4 align-items-center">

            <div class="position-relative overflow-hidden col-lg-4 text-center">
                <img class="img-fluid rounded-circle" src="{{ person.photo.url }}" style="width: 300px;"
                     alt="person_photo">
            </div>
            <div class="col-lg-8 text-white text-center">
                <h1 class="mb-3 mt-3 text-white">{{ person.get_fullname }}</h1>

                {% with administration=person.administration %}
                {% if administration %}
                <h5 class="text-white">{{ administration.position }}</h5>
                {% endif %}
                {% endwith %}

                {% with teacher=person.teacher %}
                {% if teacher %}
                <h5 class="text-white">
                    {% if person.sex %}
                    Вчитель
                    {% else %}
                    Вчителька
                    {% endif %}
                    {{ teacher.lessons.all|join:', ' }}
                </h5>
                {% endif %}
                {% endwith %}

                {% for cat in person.otherstaff.categories.all %}
                <h5 class="text-white">{{ cat }}</h5>
                {% endfor %}

                {% if info_about_teacher %}
                <p>{{ info_about_teacher }}</p>
                {% endif %}

                {% if person.life_credo %}
                <p>Життєве кредо: {{ person.life_credo }}</p>
                {% endif %}

                {% with socialnetwork=person.socialnetworkofuser_set.all %}
                {% if socialnetwork %}
                <div>
                    {% for network in socialnetwork %}
                    <a class="btn btn-outline-light text-center mr-2 px-0" style="width: 38px; height: 38px;"
                       href="{{ network.link }}" target="_blank">
                        <i class="fab fa-{{ network.type_of_social_network.class_name }}"></i>
                    </a>
                    {% endfor %}
                </div>
                {% endif %}
                {% endwith %}

            </div>
        </div>
    </div>
</div>
<!-- Header End -->

<!-- Detail Start -->
<div class="container pb-5">
    <div class="row">
        <div class="col-lg-8">
            <div class="mb-5">
                {{ person.about_me|safe }}

                <!-- Certificates block-->
                {% if certificates %}
                <table class="table">
                    <thead class="bg-primary text-white">
                    <tr class="text-center">
                        <th scope="col" class="align-middle">Назва</th>
                        <th scope="col" class="align-middle">Тип документу</th>
                        <th scope="col" class="align-middle">Платформа</th>
                        <th scope="col" class="align-middle">К-ть годин</th>
                        <th scope="col" class="align-middle">Дата видачі</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for certificate in certificates %}
                    <tr class="text-center">
                        <td class="text-left">
                            <a href="{{ certificate.link }}" target="_blank">{{ certificate.name }}</a>
                        </td>
                        <td>{{ certificate.type_doc }}</td>

                        {% if certificate.platform %}
                        {% with platform_link=certificate.platform.link %}
                        {% if platform_link %}
                        <td>
                            <a href="{{ platform_link }}" target="_blank">{{ certificate.platform }}</a>
                        </td>

                        {% else %}
                        <td>{{ certificate.platform }}</td>
                        {% endif %}
                        {% endwith %}
                        {% else %}
                        <td>---</td>
                        {% endif %}


                        {% if certificate.number_of_hours %}
                        <td>{{ certificate.number_of_hours }}</td>
                        {% else %}
                        <td>---</td>
                        {% endif %}

                        <td>{{ certificate.date|date:'Y.m.d'}}</td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
                {% endif %}
            </div>
        </div>

        <div class="col-lg-4 mt-5 mt-lg-0">

            <!-- Lessons List -->
            <div class="mb-5">
                <h2 class="mb-4">Предмети</h2>
                <ul class="list-group list-group-flush">

                    {% for lesson in lessons %}
                    <li class="list-group-item d-flex justify-content-between align-items-center px-0">
                        <a href="">{{ lesson.name|title }}</a>
                        <span class="badge badge-primary badge-pill">{{ lesson.teacher_set.count }}</span>
                    </li>
                    {% endfor %}

                </ul>
            </div>


            <!-- Category List -->
            <div class="mb-5">
                <h2 class="mb-4">Категорії</h2>
                <ul class="list-group list-group-flush">

                    {% for category in categories %}
                    <li class="list-group-item d-flex justify-content-between align-items-center px-0">
                        <a href="">{{ category.name }}</a>
                        <span class="badge badge-primary badge-pill">{{ category.teacher_set.count }}</span>
                    </li>
                    {% endfor %}

                </ul>
            </div>

            <!-- Plain Text -->
            <!--            <div>-->
            <!--                <h2 class="mb-4">Plain Text</h2>-->
            <!--                Aliquyam sed lorem stet diam dolor sed ut sit. Ut sanctus erat ea est aliquyam dolor et. Et no-->
            <!--                consetetur eos labore ea erat voluptua et. Et aliquyam dolore sed erat. Magna sanctus sed eos tempor-->
            <!--                rebum dolor, tempor takimata clita sit et elitr ut eirmod.-->
            <!--            </div>-->
        </div>
    </div>
</div>
<!-- Detail End -->

{% endblock %}

staff/templates/staff/staff.html
{% extends 'base.html' %}
{% load static %}

{% block link %}
<link href="{% static 'css/categories.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
<!-- Header Start -->
<div class="container-fluid bg-primary mb-5">
    <div class="d-flex flex-column align-items-center justify-content-center" style="min-height: 400px">
        <h3 class="display-3 font-weight-bold text-white">Наш колектив</h3>
        <div class="d-inline-flex text-white">
            <span><a class="text-white" href="{% url 'index' %}">Головна</a></span>
            <span class="px-2">/</span>
            <span><a class="text-white" href="{% url 'staff' %}">Наш колектив</a></span>
            {% if active_category %}
            <span class="px-2">/</span>
            <span>{{ active_category }}</span>
            {% endif %}
        </div>
    </div>
</div>
<!-- Header End -->

<!-- Team Start -->
<div class="container-fluid pt-5">
    <div class="container">
        <div class="text-center pb-2">
            <p class="section-title px-5"><span class="px-2">Наша команда</span></p>
            <h1 class="mb-4">Зустрічай нашу команду</h1>
        </div>


        <div class="row">
            <div class="col-12 text-center mb-2">
                <div class="list-inline mb-4" id="portfolio-flters">
                    <a class="btn category_link m-1 category_link_active" href="{% url 'staff' %}">Всі</a>
                    <a class="btn category_link m-1" href="{% url 'staff' %}?cat=Адміністрація">Адміністрація</a>
                    <a class="btn category_link m-1" href="{% url 'staff' %}?cat=Вчителі">Вчителі</a>
                    {% for cat in cat_other_staff %}
                    {% with count=cat.otherstaff_set.count %}
                    {% if count > 1 %}
                    <a class="btn category_link m-1" href="{% url 'staff' %}?cat={{ cat.names }}">{{ cat.names }}</a>
                    {% elif count == 1 %}
                    <a class="btn category_link m-1" href="{% url 'staff' %}?cat={{ cat.name }}">{{ cat.name }}</a>
                    {% endif %}
                    {% endwith %}
                    {% endfor %}
                </div>
            </div>
        </div>

        <div class="row">
            {% for person in persons %}
            <div class="col-md-6 col-lg-3 text-center team mb-5">
                <a href="{% url 'staff_detail' person.pk %}">
                    <div class="position-relative overflow-hidden mb-4" style="border-radius: 100%;">
                        <img class="img-fluid w-100" src="{{ person.photo.url }}" alt="person_photo">
                    </div>
                    <h4>{{ person.get_fullname }}</h4>
                </a>

                {% with administration=person.administration %}
                {% if administration %}
                <i>{{ administration.position }}</i><br>
                {% endif %}
                {% endwith %}
                {% with teacher=person.teacher %}
                {% if teacher %}
                <i>
                    {% if person.sex %}
                    Вчитель
                    {% else %}
                    Вчителька
                    {% endif %}
                    {{ teacher.lessons.all|join:', ' }}
                </i><br>
                {% endif %}
                {% endwith %}

                {% for cat in person.otherstaff.categories.all %}
                <i>{{ cat }}</i><br>
                {% endfor %}

            </div>
            {% endfor %}

        </div>
    </div>
</div>
<!-- Team End -->


{% endblock %}
{% block script %}
let active_category = '{{ active_category }}';
let children_cat = document.getElementById('portfolio-flters').children;
for (let i = 1; i < children_cat.length; i++) {
if (children_cat[i].text == active_category) {
children_cat[i].classList.toggle('category_link_active');
children_cat[0].classList.toggle('category_link_active');
break;
}
}
{% endblock %}